apiVersion: v1
kind: Service
metadata:
  name: < your name > #eg anchore-ui-lb
  annotations:
          networking.gke.io/load-balancer-type: "Internal"
  namespace: < your namespace > #eg anchore
spec:
  ports:
  - name: <port name>     #anchore-enterprise-ui-web
    protocol: TCP
    targetPort: 3000
    port: 80
  selector:
    app: <selector># eg anchore-dmj-anchore-engine
    component: enterprise-ui
  type: LoadBalancer
